language: "node_js"
node_js:
- '6.11'
script:
- yarn install
- npm run test
env:
- CXX=g++-4.8
branches:
  only:
  - master
deploy:
  provider: npm
  email: sgmeyer@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
